# .cpanel.yml
deployment:
  tasks:
    - export DEPLOY_PATH=/home/$USER/public_html # Path ke direktori deployment
    - echo "Building React App..."
    - npm install --legacy-peer-deps # Install dependensi
    - npm run build # Build aplikasi React
    - echo "Deploying React App..."
    - rm -rf $DEPLOY_PATH/* # Hapus file lama di direktori deployment
    - cp -R build/* $DEPLOY_PATH/ # Salin file hasil build ke direktori publik
    - echo "Deployment Completed!"
